[book]
title = "Algorand Specifications"
authors = ["Algorand Foundation"]
description = "Algorand normative and non-normative specifications"
src = "src"
language = "en"
text-direction = "ltr"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "dark"
smart-punctuation = true
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js", "gtm.js", "gtm-noscript.js", "theme/sidebar-active-link.js"]
additional-css = ["theme-override.css"]
git-repository-url = "https://github.com/algorandfoundation/specs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/algorandfoundation/specs/edit/master/{path}"
site-url = "https://specs.algorand.co/"

[output.html.fold]
enable = true
level = 3  # Navigation sidebar unfolded up to the 4th 0-based level. Tune it according to the max SUMMARY.md level depth.

[output.pandoc]
optional = true

[output.pandoc.profile.pdf]
output-file = "algorand-specs.pdf"
pdf-engine = "lualatex"
filters = ["mermaid-filter"]

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = ["NotoColorEmoji:mode=harf", "Noto Sans Symbols:mode=harf", "Noto Sans Symbols2:mode=harf"]
sansfontfallback = ["NotoColorEmoji:mode=harf", "Noto Sans Symbols:mode=harf", "Noto Sans Symbols2:mode=harf"]
monofontfallback = ["NotoColorEmoji:mode=harf", "Noto Sans Symbols:mode=harf", "Noto Sans Symbols2:mode=harf"]
